### ISSUE TITLE
Countdown to making repo public

### ISSUE THREAD

**Issue by j-harbin** [dankelley/argoFloats#56]
As discussed at an ftf recently, this package is getting close enough to completion that we can make it public soon (sometime next week).

Here is a checklist (This might be updated later)

* [x] Remove any issue that has confidential information
* [x] Write a show method 
* [x] Write the beginnings of a plot method
* ~[ ] Create method for subsetting to deep argo~
* [x] Update all documentation to use built in data sets
* [x] Fill in content for `?argoFloats-package`

**Comment by dankelley** [comment]
I'm closing this, because we had an f2f for a final check, and then I made it public.

Also, I set up travisCI, appveyor, and codecov tests.
