### ISSUE TITLE
First video creation

### ISSUE THREAD

**Issue by j-harbin** [dankelley/argoFloats#57]
As discussed in the ftf with @dankelley its suggested that our first video include installing `devtools`, installing `argoFloats` package through github, drawing attention to our `argoFloats-package` which will include our three steps : `getIndex()`, `getProfiles()`, `readProfiles()`.

**Comment by dankelley** [comment]
The first video has been made, and is posted at https://youtu.be/xeBoFbb66Nk so I'm closing this issue.  Thanks!
