### ISSUE TITLE
Allowing for multiple type of subsetting at the same time

### ISSUE THREAD

**Issue by j-harbin** [dankelley/argoFloats#66]
As discussed in the ftf with @dankelley , allowing the user to subset by more than one way at once would be nice.

**Comment by dankelley** [comment]
I propose workflow:
```R
library(argoFloats)
i <- getIndex(...)
i1 <- subset(i, ...)
i2 <- subset(i, ...)
i12 <- merge(i1, 2)
```

NOTE: `merge` is a generic function.  I'll try making that today, and if I get it working, we'll want to mention it in the vignette.  I'll post again here if I get it working.

**Comment by dankelley** [comment]
I've coded this, and merged it into the "develop" branch. The following (from the help page) produces as shown.  I think this is an acceptable solution to the issue, but -- as usual -- it's up to the reporter to decide.

```R
library(argoFloats)
data(index)

# Index of floats within 50km of Abaca Island
C <- subset(index, circle=list(longitude=-77.5, latitude=27.5, radius=50))

# Index of floats within a rectangle near Abaca Island
lonRect <- c(-76.5, -76)
latRect <- c(26.5, 27.5)
R <- subset(index, rectangle=list(longitude=lonRect, latitude=latRect))

RC <- merge(C, R)
plot(RC)
```

![a](https://user-images.githubusercontent.com/99469/79783627-52829f00-8317-11ea-8fae-55644fcc7a16.png)

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.
